name: web3dart
description: Dart library to connect to Ethereum clients. Send transactions and interact with smart contracts!
version: 2.0.0-dev.10
publish_to: none
homepage: https://github.com/simolus3/web3dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  pointycastle: ^3.0.0-nullsafety.2
  convert: ^3.0.0
  meta: ^1.1.0
  http: ^0.13.0
  uuid: ^3.0.1
  isolate: 
    git:
      url: https://github.com/redDwarf03/isolate.git
      ref: master
  typed_data: ^1.1.6
  stream_channel: ^2.0.0
  json_rpc_2: 
    git:
      url: https://github.com/redDwarf03/json_rpc_2.git
      ref: master
  collection: ^1.14.11

dev_dependencies:
  web_socket_channel: ^2.0.0
  path: ^1.6.2
  test: ^1.9.0
  mockito: ^5.0.2
  coverage: ^1.0.2
